spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    url: ${POSTGRES_URL}

  jpa:
    properties:
      hibernate:
        default_schema: audits
    hibernate:
      ddl-auto: none

feign:
  url:
    users: ${FEIGN_USER}

